import { Cotizacion } from "./types";

export const cotizacionesEjemplo: Cotizacion[] = [
  {
    id: "1",
    numeroCotizacion: "COT-2024-001",
    nombreServicio: "Limpieza General de Oficinas",
    cliente: "Corporativo Alfa S.A. de C.V.",
    proveedor: "CleanPro México",
    monto: 45000,
    fechaSolicitud: "2024-01-10",
    fechaEnvio: "2024-01-12",
    fechaCierreEstimada: "",
    responsable: "Diego Rodríguez",
    estado: "aprobada",
    proximaAccion: "Coordinar inicio de servicios",
    notas: "Cliente solicita servicio mensual recurrente. Frecuencia: 3 veces por semana.",
    enlaceSheets: "https://docs.google.com/spreadsheets/d/ejemplo1",
    categoria: "Limpieza General",
    prioridad: "Alta",
    probabilidadCierre: 100,
    motivoRechazo: "",
    creadoEn: "2024-01-10T09:00:00Z",
    actualizadoEn: "2024-01-20T14:00:00Z",
  },
  {
    id: "2",
    numeroCotizacion: "COT-2024-002",
    nombreServicio: "Mantenimiento Preventivo HVAC",
    cliente: "Hospital Médico Central",
    proveedor: "TecnoClima Industrial",
    monto: 128500,
    fechaSolicitud: "2024-01-15",
    fechaEnvio: "2024-01-18",
    fechaCierreEstimada: "",
    responsable: "Patricio Blanco",
    estado: "enviada",
    proximaAccion: "Llamar al director de mantenimiento el lunes",
    notas: "Requiere acceso a áreas restringidas. Coordinar con seguridad.",
    enlaceSheets: "https://docs.google.com/spreadsheets/d/ejemplo2",
    categoria: "Instalación",
    prioridad: "Alta",
    probabilidadCierre: 75,
    motivoRechazo: "",
    creadoEn: "2024-01-15T10:30:00Z",
    actualizadoEn: "2024-01-18T16:00:00Z",
  },
  {
    id: "3",
    numeroCotizacion: "COT-2024-003",
    nombreServicio: "Servicio de Seguridad Perimetral",
    cliente: "Bodega Industrial Norte",
    proveedor: "SecureGuard México",
    monto: 89000,
    fechaSolicitud: "2024-01-20",
    fechaEnvio: "",
    fechaCierreEstimada: "",
    responsable: "Diego Rodríguez",
    estado: "pendiente",
    proximaAccion: "Visita a sitio para levantamiento el miércoles",
    notas: "Necesitan 4 guardias 24/7. Incluir propuesta de cámaras.",
    enlaceSheets: "",
    categoria: "Instalación",
    prioridad: "Alta",
    probabilidadCierre: 60,
    motivoRechazo: "",
    creadoEn: "2024-01-20T08:00:00Z",
    actualizadoEn: "2024-01-20T08:00:00Z",
  },
  {
    id: "4",
    numeroCotizacion: "COT-2024-004",
    nombreServicio: "Jardinería y Mantenimiento de Áreas Verdes",
    cliente: "Residencial Las Palmas",
    proveedor: "Verde Naturaleza",
    monto: 32000,
    fechaSolicitud: "2024-01-08",
    fechaEnvio: "2024-01-09",
    fechaCierreEstimada: "",
    responsable: "Patricio Blanco",
    estado: "rechazada",
    proximaAccion: "Archivar. Posible seguimiento en Q2.",
    notas: "El cliente eligió un proveedor local con menor precio.",
    enlaceSheets: "https://docs.google.com/spreadsheets/d/ejemplo4",
    categoria: "Limpieza General",
    prioridad: "Baja",
    probabilidadCierre: 0,
    motivoRechazo: "Precio elevado vs. competencia local",
    creadoEn: "2024-01-08T11:00:00Z",
    actualizadoEn: "2024-01-22T09:00:00Z",
  },
  {
    id: "5",
    numeroCotizacion: "COT-2024-005",
    nombreServicio: "Fumigación y Control de Plagas",
    cliente: "Restaurante El Buen Sabor",
    proveedor: "EcoControl Plagas",
    monto: 15500,
    fechaSolicitud: "2024-01-22",
    fechaEnvio: "2024-01-23",
    fechaCierreEstimada: "",
    responsable: "Diego Rodríguez",
    estado: "enviada",
    proximaAccion: "Confirmar fecha de aplicación con encargado",
    notas: "Servicio urgente por requisito de certificación sanitaria.",
    enlaceSheets: "https://docs.google.com/spreadsheets/d/ejemplo5",
    categoria: "Fumigación",
    prioridad: "Alta",
    probabilidadCierre: 90,
    motivoRechazo: "",
    creadoEn: "2024-01-22T14:00:00Z",
    actualizadoEn: "2024-01-23T10:00:00Z",
  },
  {
    id: "6",
    numeroCotizacion: "COT-2024-006",
    nombreServicio: "Instalación Eléctrica Industrial",
    cliente: "Planta Manufacturera Beta",
    proveedor: "ElectroSoluciones MX",
    monto: 215000,
    fechaSolicitud: "2024-01-25",
    fechaEnvio: "",
    fechaCierreEstimada: "",
    responsable: "Patricio Blanco",
    estado: "pendiente",
    proximaAccion: "Solicitar planos eléctricos al cliente",
    notas: "Proyecto en 2 fases. Fase 1: subestación. Fase 2: distribución.",
    enlaceSheets: "",
    categoria: "Electricidad",
    prioridad: "Alta",
    probabilidadCierre: 50,
    motivoRechazo: "",
    creadoEn: "2024-01-25T09:30:00Z",
    actualizadoEn: "2024-01-25T09:30:00Z",
  },
  {
    id: "7",
    numeroCotizacion: "COT-2024-007",
    nombreServicio: "Pintura Exterior de Edificio",
    cliente: "Torre Empresarial Sur",
    proveedor: "PintaMex Profesional",
    monto: 67000,
    fechaSolicitud: "2024-01-18",
    fechaEnvio: "2024-01-21",
    fechaCierreEstimada: "",
    responsable: "Diego Rodríguez",
    estado: "aprobada",
    proximaAccion: "Coordinar inicio de obra",
    notas: "Color RAL 9003. Incluye andamios y equipo de seguridad.",
    enlaceSheets: "https://docs.google.com/spreadsheets/d/ejemplo7",
    categoria: "Limpieza Profunda",
    prioridad: "Media",
    probabilidadCierre: 100,
    motivoRechazo: "",
    creadoEn: "2024-01-18T10:00:00Z",
    actualizadoEn: "2024-01-28T15:00:00Z",
  },
  {
    id: "8",
    numeroCotizacion: "COT-2024-008",
    nombreServicio: "Plomería y Reparación de Red Hidráulica",
    cliente: "Centro Comercial Estrella",
    proveedor: "HidroExpert",
    monto: 38500,
    fechaSolicitud: "2024-01-28",
    fechaEnvio: "2024-01-29",
    fechaCierreEstimada: "",
    responsable: "Diego Rodríguez",
    estado: "enviada",
    proximaAccion: "Seguimiento por WhatsApp al gerente de operaciones",
    notas: "Fuga detectada en nivel -2. Trabajo nocturno requerido.",
    enlaceSheets: "https://docs.google.com/spreadsheets/d/ejemplo8",
    categoria: "Plomería",
    prioridad: "Alta",
    probabilidadCierre: 80,
    motivoRechazo: "",
    creadoEn: "2024-01-28T16:00:00Z",
    actualizadoEn: "2024-01-29T11:00:00Z",
  },
  {
    id: "9",
    numeroCotizacion: "COT-2024-009",
    nombreServicio: "Limpieza de Tanques de Agua",
    cliente: "Condominio Las Torres",
    proveedor: "CleanPro México",
    monto: 12000,
    fechaSolicitud: "2024-01-30",
    fechaEnvio: "",
    fechaCierreEstimada: "",
    responsable: "Patricio Blanco",
    estado: "pendiente",
    proximaAccion: "Enviar cotización esta semana",
    notas: "4 cisternas de 10,000 litros cada una.",
    enlaceSheets: "",
    categoria: "Limpieza",
    prioridad: "Media",
    probabilidadCierre: 70,
    motivoRechazo: "",
    creadoEn: "2024-01-30T09:00:00Z",
    actualizadoEn: "2024-01-30T09:00:00Z",
  },
  {
    id: "10",
    numeroCotizacion: "COT-2024-010",
    nombreServicio: "Consultoría en Gestión de Facilities",
    cliente: "Grupo Empresarial Omega",
    proveedor: "SERVA Consulting",
    monto: 95000,
    fechaSolicitud: "2024-01-05",
    fechaEnvio: "2024-01-07",
    fechaCierreEstimada: "",
    responsable: "Diego Rodríguez",
    estado: "rechazada",
    proximaAccion: "Revisar propuesta mejorada para Q2",
    notas: "Presupuesto aprobado fue 30% menor. Considerar propuesta reducida.",
    enlaceSheets: "https://docs.google.com/spreadsheets/d/ejemplo10",
    categoria: "Instalación",
    prioridad: "Media",
    probabilidadCierre: 0,
    motivoRechazo: "Presupuesto insuficiente del cliente",
    creadoEn: "2024-01-05T10:00:00Z",
    actualizadoEn: "2024-01-26T12:00:00Z",
  },
];
